### ISSUE TITLE
Exception on /feeder_gateway/get_block_traces with --fork-network "alpha-goerli"

### ISSUE THREAD

**Issue by mikiw** [0xSpaceShard/starknet-devnet#418]
**Describe the bug (observed vs expected behavior)**

When I run devnet:
```
poetry run starknet-devnet --seed 42 --accounts 1 --fork-network "alpha-goerli"
```
and later I try to connect with starkscan `https://devnet.starkscan.co/` I have this Exception:
```
[2023-03-09 14:50:25 +0100] [3314] [ERROR] Exception on /feeder_gateway/get_block_traces [GET]
Traceback (most recent call last):
  File "/home/mikiw/.cache/pypoetry/virtualenvs/starknet-devnet-Xwx3J2b3-py3.8/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mikiw/.cache/pypoetry/virtualenvs/starknet-devnet-Xwx3J2b3-py3.8/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mikiw/.cache/pypoetry/virtualenvs/starknet-devnet-Xwx3J2b3-py3.8/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/mikiw/.cache/pypoetry/virtualenvs/starknet-devnet-Xwx3J2b3-py3.8/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mikiw/.cache/pypoetry/virtualenvs/starknet-devnet-Xwx3J2b3-py3.8/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/mikiw/.cache/pypoetry/virtualenvs/starknet-devnet-Xwx3J2b3-py3.8/lib/python3.8/site-packages/asgiref/sync.py", line 240, in __call__
    return call_result.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/mikiw/.cache/pypoetry/virtualenvs/starknet-devnet-Xwx3J2b3-py3.8/lib/python3.8/site-packages/asgiref/sync.py", line 306, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/mnt/c/Workspace/ShardLabs/starknet-devnet/starknet_devnet/blueprints/feeder_gateway.py", line 158, in get_block_traces
    block_transaction_traces = await _get_block_transaction_traces(block)
  File "/mnt/c/Workspace/ShardLabs/starknet-devnet/starknet_devnet/blueprints/feeder_gateway.py", line 86, in _get_block_transaction_traces
    if block.transaction_receipts:
AttributeError: 'NoneType' object has no attribute 'transaction_receipts'
```

Is it because `transaction_receipts` are missing from `http://localhost:5050/feeder_gateway/get_block_traces?blockNumber=pending` ?

**Not reproducible on alpha-goerli**

- [ ] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**To Reproduce**

1. Run devnet `poetry run starknet-devnet --seed 42 --accounts 1 --fork-network "alpha-goerli"`
2. Call `http://localhost:5050/feeder_gateway/get_block?blockHash=0x7d328a71faf48c5c3857e99f20a77b18522480956d1cd5bff1ff2df3c8b427b` there is 500

**Devnet version**

- I am using Devnet version:
- [ ] This happens with a dockerized Devnet (check the box if true).
- This does not appear on the following Devnet version:

**System specifications**

- OS:
- CPU:
- Memory:
- Python version:

**Comment by mikiw** [comment]
so https://github.com/Shard-Labs/starknet-devnet/pull/419 fix was merged

now when new version will be released we will ask starkscan team to check this issue

**Comment by mikiw** [comment]
new version was released so now I'll ask starkscan team to look into it

**Comment by mikiw** [comment]
It's on starkscan team roadmap but still, not fixed.
