### ISSUE TITLE
Cairo 1 contract deployment

### ISSUE THREAD

**Issue by piwonskp** [0xSpaceShard/starknet-devnet#448]
Hey, we are trying to integrate devnet with [warp](https://github.com/NethermindEth/warp) for testing, but we're having trouble in deploying cairo 1 contracts. Could you explain how to do that?

**Describe the bug (observed vs expected behavior)**

Contract deployment results in error:
```
Got BadRequest while trying to access http://devnet:5050/feeder_gateway/simulate_transaction?blockNumber=pending&skipValidate=false. Status code: 500; text: {"code":"StarknetErrorCode.ENTRY_POINT_NOT_FOUND_IN_CONTRACT","message":"Error at pc=0:81:\nGot an exception while executing a hint.\nCairo traceback (most recent call last):\nUnknown location (pc=0:731)\nUnknown location (pc=0:677)\nUnknown location (pc=0:291)\nUnknown location (pc=0:314)\n\nError in the called contract (0x7e00d496e324876bbc8531f2d9a82bf154d1a04a50218ee74cdd372f75a551a):\nEntry point 0x2730079d734ee55315f4f141eaed376bddd8c2133523d223a344c5604e0f7f8 not found in contract with class hash 0x4d07e40e93398ed3c76981e72dd1fd22557a78ce36c0515f679e27f0bb5bc5f."}
.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/services/external_api/client.py", line 187, in _send_request
    return await self._parse_response(
  File "/usr/local/lib/python3.9/dist-packages/services/external_api/client.py", line 231, in _parse_response
    raise BadRequest(status_code=response.status, text=text)
services.external_api.client.BadRequest: HTTP error ocurred. Status: 500. Text: {"code":"StarknetErrorCode.ENTRY_POINT_NOT_FOUND_IN_CONTRACT","message":"Error at pc=0:81:\nGot an exception while executing a hint.\nCairo traceback (most recent call last):\nUnknown location (pc=0:731)\nUnknown location (pc=0:677)\nUnknown location (pc=0:291)\nUnknown location (pc=0:314)\n\nError in the called contract (0x7e00d496e324876bbc8531f2d9a82bf154d1a04a50218ee74cdd372f75a551a):\nEntry point 0x2730079d734ee55315f4f141eaed376bddd8c2133523d223a344c5604e0f7f8 not found in contract with class hash 0x4d07e40e93398ed3c76981e72dd1fd22557a78ce36c0515f679e27f0bb5bc5f."}

Error: BadRequest: HTTP error ocurred. Status: 500. Text: {"code":"StarknetErrorCode.ENTRY_POINT_NOT_FOUND_IN_CONTRACT","message":"Error at pc=0:81:\nGot an exception while executing a hint.\nCairo traceback (most recent call last):\nUnknown location (pc=0:731)\nUnknown location (pc=0:677)\nUnknown location (pc=0:291)\nUnknown location (pc=0:314)\n\nError in the called contract (0x7e00d496e324876bbc8531f2d9a82bf154d1a04a50218ee74cdd372f75a551a):\nEntry point 0x2730079d734ee55315f4f141eaed376bddd8c2133523d223a344c5604e0f7f8 not found in contract with class hash 0x4d07e40e93398ed3c76981e72dd1fd22557a78ce36c0515f679e27f0bb5bc5f."}
```

**To Reproduce**

1. Contract:
```
#[contract] 
mod T {
    #[external]
    fn foo(a: u8){
    }

    #[constructor]
    fn constructor(){
    }
}
```
2. Compile using `starknet-compile`: `starknet-compile tst.cairo tst.json`
3.  Declare: `starknet declare --contract tst.json --gateway_url http://devnet:5050 --feeder_gateway_url http://devnet:5050`
4.  Try to deploy: `starknet deploy --gateway_url http://devnet:5050 --feeder_gateway_url http://devnet:5050 --class_hash 0x454cd262569a3af622e6a60a01eb1e64e1965308aee3ea4ae951ed0dddb2637 --wallet starkware.starknet.wallets.open_zeppelin.OpenZeppelinAccount --account_dir /usr/src/warp/.starknet_accounts_devnet --network alpha-goerli`

`devnet` is the name of the [container](https://github.com/NethermindEth/warp/blob/develop/docker-compose.yaml#L15)

**Devnet version**

- I am using Devnet version: 0.5.0
- [x] This happens with a dockerized Devnet (check the box if true).
- We are using cairo-lang 0.11.0.2

**Comment by FabijanC** [comment]
I see that entrypoint `0x2730079d734ee55315f4f141eaed376bddd8c2133523d223a344c5604e0f7f8` is reported as not being present in class with hash `0x4d07e40e93398ed3c76981e72dd1fd22557a78ce36c0515f679e27f0bb5bc5f`.

The class hash refers to the OpenZeppelin class used for the set of predeployed accounts in Devnet. This is distinct from the default class used by Starknet CLI (they call it modified OpenZeppelin). The entrypoint reported refers to `deploy_contract` (checked using [starkli](https://github.com/xJonathanLEI/starkli): `starkli selector deploy_contract`); this entrypoint exists on Starknet CLI's account class, and doesn't exist on the class used by predeployed accounts.

Solutions that come to mnd:
1. Deploy an account using Starknet CLI (which Starknet CLI will then know how to interact with)
2. Use a different client: instead of Starknet CLI, something which can work with accounts other than Starknet CLI's default account class.

**Comment by piwonskp** [comment]
Following your advice I've deployed a new account:

```
root@e88a44afca84:/usr/src/warp# starknet new_account --gateway_url http://devnet:5050 --feeder_gateway_url http://devnet:5050
Account address: 0x024b5b05781d6661f1cb6961a25a3bb96c55250b89b8d029601c138af010edd6
Public key: 0x0112274494559a6c52fc54b7816b4fad064c83507414db61816bff4343c2d30c
Move the appropriate amount of funds to the account, and then deploy the account
by invoking the 'starknet deploy_account' command.

NOTE: This is a modified version of the OpenZeppelin account contract. The signature is computed
differently.

root@e88a44afca84:/usr/src/warp# starknet deploy_account --gateway_url http://devnet:5050 --feeder_gateway_url http://devnet:5050
Sending the transaction with max_fee: 0.000476 ETH (475530000000001 WEI).
Sent deploy account contract transaction.

Contract address: 0x024b5b05781d6661f1cb6961a25a3bb96c55250b89b8d029601c138af010edd6
Transaction hash: 0x7d73e76dfc24c7f42dbd223c43edf77fce9ca8e14eb5994883d72d25516fe6c

```
Now declare is not working:
```
starknet declare --contract tst.json --gateway_url http://devnet:5050 --feeder_gateway_url http://devnet:5050
Got BadRequest while trying to access http://devnet:5050/feeder_gateway/simulate_transaction?blockNumber=pending&skipValidate=false. Status code: 500; text: {"code":"StarknetErrorCode.UNINITIALIZED_CONTRACT","message":"Requested contract address 0x24b5b05781d6661f1cb6961a25a3bb96c55250b89b8d029601c138af010edd6 is not deployed."}
.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/services/external_api/client.py", line 187, in _send_request
    return await self._parse_response(
  File "/usr/local/lib/python3.9/dist-packages/services/external_api/client.py", line 231, in _parse_response
    raise BadRequest(status_code=response.status, text=text)
services.external_api.client.BadRequest: HTTP error ocurred. Status: 500. Text: {"code":"StarknetErrorCode.UNINITIALIZED_CONTRACT","message":"Requested contract address 0x24b5b05781d6661f1cb6961a25a3bb96c55250b89b8d029601c138af010edd6 is not deployed."}

Error: BadRequest: HTTP error ocurred. Status: 500. Text: {"code":"StarknetErrorCode.UNINITIALIZED_CONTRACT","message":"Requested contract address 0x24b5b05781d6661f1cb6961a25a3bb96c55250b89b8d029601c138af010edd6 is not deployed."}
```

**Comment by FabijanC** [comment]
You probably need to fund your account. This has already been discussed: https://github.com/0xSpaceShard/starknet-devnet/issues/431#issuecomment-1494014853

**Comment by piwonskp** [comment]
Ok, thanks I will try it

**Comment by FabijanC** [comment]
I'll take it that this has been resolved. @piwonskp If you disagree, please reopen.

**Comment by piwonskp** [comment]
It worked, thanks!
