### ISSUE TITLE
Getting error when querying JSON RPC

### ISSUE THREAD

**Issue by amanusk** [0xSpaceShard/starknet-devnet#477]
**Describe the bug (observed vs expected behavior)**

When trying to query using `starknet-js`, I am able to query when using the sequencer API, but getting error when querying with JSON RPC.

Querying with `SequencerProvider` does work

**Not reproducible on alpha-goerli**

- [X] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**To Reproduce**

1. Start decent with `starknet-devent --seed 0`
1. Configure provider:
```
const provider = new RpcProvider({
    nodeUrl: "HTTP://127.0.0.1:5050,
});
```
2. Query a balance with the code:
```static async getBalance(address: string, provider: ProviderInterface, tokenAddress?: string): Promise<BigInt> {
    if (tokenAddress == null) {
      tokenAddress = DEFAULT_TOKEN_ADDRESS;
    }
    const erc20ABI = json.parse(fs.readFileSync("./src/interfaces/ERC20_abi.json").toString("ascii"));
    const erc20 = new Contract(erc20ABI, tokenAddress, provider);
    const balance = await erc20.balanceOf("0x7f61fa3893ad0637b2ff76fed23ebbb91835aacd4f743c2347716f856438429");
    let balanceBigNumber = uint256.uint256ToBN(balance.balance);
    return balanceBigNumber;
  }
```

Get response
```
FetchError: invalid json response body at http://127.0.0.1:5050/ reason: Unexpected token < in JSON at position 0
```

**Devnet version**

- I am using Devnet version:
- [ ] This happens with a dockerized Devnet (check the box if true).
- This does not appear on the following Devnet version:

**System specifications**

- OS: Ubuntu
- CPU: Intel
- Memory:32
- Python version: 3.9

**Comment by mikiw** [comment]
Hi @amanusk I can reproduce it on my local and I'll take a look into it.

**Comment by mikiw** [comment]
self.__latest_state is set to `None` at the initialization of `StarknetWrapper` so if you do this workaround:

1. termial 1: `poetry run starknet-devnet --seed 0`
2. terminal 2: `create_empty_block` or mint with `curl -X POST http://localhost:5050/mint -d '{"address": "0x232c289f2500c1e508b2245e3ca43368bce4aac03588435c529eff7683bfb59", "amount": 123412341234123412341234}' -H 'Content-Type: application/json'
{"new_balance":123412341234123412341234,"tx_hash":"0x912acf8a73526d6fcfe0c3372ae3331cc5acfd86b9cf812e75a7d9975488b7","unit":"wei"}`
3. terminal 3: run a program from above `node myOwnTest.js`

**Comment by amanusk** [comment]
Related issue, tell me if I should open a new bug for that.
Fetching the balance actually works for me now after adding the `/rpc` route (my bad, forgot about it).
Now I get errors when trying to execute and `INVOKE` function.

Again, works fine with sequencer provider, and works with remote RPCs, but does not work with JSON RPC on devenet.

Code for invoke:
```  async transfer(recipientAddress: string, amount: BigInt, tokenAddress?: string, decimals: number = 18) {
    if (tokenAddress == null) {
      tokenAddress = DEFAULT_TOKEN_ADDRESS;
    }

    const erc20ABI = json.parse(fs.readFileSync("./src/interfaces/ERC20_abi.json").toString("ascii"));
    const erc20 = new Contract(erc20ABI, tokenAddress, this.account);

    let uint256Amount = uint256.bnToUint256(amount.valueOf());

    let estimateFee = await this.account.estimateInvokeFee({
--
      entrypoint: "transfer",
      calldata: [recipientAddress, uint256Amount.low, uint256Amount.high],
    });
    prettyPrintFee(estimateFee);

    const { transaction_hash: transferTxHash } = await this.account.execute(
      {
        contractAddress: tokenAddress,
        entrypoint: "transfer",
        calldata: [recipientAddress, uint256Amount.low, uint256Amount.high],
      },
      undefined, // abi
      { maxFee: estimateFee.suggestedMaxFee },
    );
    console.log("Awaiting tx ", transferTxHash);
    await this.account.waitForTransaction(transferTxHash);
    console.log("Tx mined ", transferTxHash);
  }
```

Returned error:/home/amanusk/Code/Cairo/starknet-cli-wallet/node_modules/starknet/src/provider/rpc.ts:85
      throw new LibraryError(`${code}: ${message}`);
            ^
LibraryError: 22: string indices must be integers
    at RpcProvider.errorHandler (/home/amanusk/Code/Cairo/starknet-cli-wallet/node_modules/starknet/src/provider/rpc.ts:85:13)
    at RpcProvider.fetchEndpoint (/home/amanusk/Code/Cairo/starknet-cli-wallet/node_modules/starknet/src/provider/rpc.ts:96:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Account.estimateInvokeFee (/home/amanusk/Code/Cairo/starknet-cli-wallet/node_modules/starknet/src/account/default.ts:107:22)
    at async StarkNetWallet.transfer (/home/amanusk/Code/Cairo/starknet-cli-wallet/src/StarkNetWallet.ts:157:23)
    at async Command.<anonymous> (/home/amanusk/Code/Cairo/starknet-cli-wallet/src/index.ts:73:5)
    ```
```

**Comment by FabijanC** [comment]
@amanusk Are we sure this is a Devnet issue? I.e. is starknet.js failing because it received an invalid response from Devnet's RPC handler? Have you tried other JSON RPC providers/nodes?

Also, what do you mean with
> works with remote RPCs, but does not work with JSON RPC on devenet

What are remote RPCs? Aren't all RPCs remote (as in - remote procedure calls)? Or do you mean other JSON-RPC nodes?

**Comment by amanusk** [comment]
@FabijanC, yes I mean other JSON-RPC nodes (infura/pathfinder), sorry if I was unclear.

**Comment by mikiw** [comment]
It's odd to me that I can get these errors when I just try call `balanceOf()`:

```
/mnt/c/Workspace/ShardLabs/starknet.js-example/node_modules/starknet/dist/index.js:4942
      throw new Error(`Nonce is required when invoking a function without an account`);
            ^

Error: Nonce is required when invoking a function without an account
    at Contract.invoke (/mnt/c/Workspace/ShardLabs/starknet.js-example/node_modules/starknet/dist/index.js:4942:13)
    at Contract.balanceOf (/mnt/c/Workspace/ShardLabs/starknet.js-example/node_modules/starknet/dist/index.js:4796:21)
    at main (/mnt/c/Workspace/ShardLabs/starknet.js-example/myOwnTest.js:22:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by mikiw** [comment]
Seems that problem is with `estimate_fee` function, can you confirm guys that these parameters are ok?
```
{'request': {'type': 'INVOKE', 'sender_address': '0x7e00d496e324876bbc8531f2d9a82bf154d1a04a50218ee74cdd372f75a551a', 'calldata': ['0x1', '0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7', '0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e', '0x0', '0x1', '0x1', '0x7e00d496e324876bbc8531f2d9a82bf154d1a04a50218ee74cdd372f75a551a'], 'signature': ['0x585ebd4df011ad6b508c6c3ce2184c7e873f0f04710f9da2d05718a07ad59c2', '0xee7f29c0ead68bc6718a52afe5b02544cf9664fc1e2e78a5ffd5be0958ddb9'], 'version': '0x100000000000000000000000000000001', 'nonce': '0x0', 'max_fee': '0x0'}, 'block_id': 'latest'}
``

full debug log
```
[2023-05-25 17:02:37 +0200] [9575] [INFO] 127.0.0.1 - - [25/May/2023:17:02:37 +0200] "POST /rpc HTTP/1.1" 200 40 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
INVALID_PARAMS
method
<function estimate_fee at 0x7fa2a7110670>
params
{'request': {'type': 'INVOKE', 'sender_address': '0x7e00d496e324876bbc8531f2d9a82bf154d1a04a50218ee74cdd372f75a551a', 'calldata': ['0x1', '0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7', '0x2e4263afad30923c891518314c3c95dbe830a16874e8abc5777a9a20b54c76e', '0x0', '0x1', '0x1', '0x7e00d496e324876bbc8531f2d9a82bf154d1a04a50218ee74cdd372f75a551a'], 'signature': ['0x585ebd4df011ad6b508c6c3ce2184c7e873f0f04710f9da2d05718a07ad59c2', '0xee7f29c0ead68bc6718a52afe5b02544cf9664fc1e2e78a5ffd5be0958ddb9'], 'version': '0x100000000000000000000000000000001', 'nonce': '0x0', 'max_fee': '0x0'}, 'block_id': 'latest'}
request block_id
<coroutine object estimate_fee at 0x7fa2a68d9540>
/mnt/c/Workspace/ShardLabs/starknet-devnet/starknet_devnet/blueprints/rpc/routes.py:111: RuntimeWarning: coroutine 'estimate_fee' was never awaited
  print(method(*params))
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
[2023-05-25 17:02:37 +0200] [9575] [INFO] 127.0.0.1 - - [25/May/2023:17:02:37 +0200] "POST /rpc HTTP/1.1" 200 712 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
```

**Comment by mikiw** [comment]
ok seems that {'request': should be array [] not object {}

**Comment by mikiw** [comment]
@amanusk current version of devnet use v0.3.0 of rpc specification:
https://github.com/starkware-libs/starknet-specs/blob/v0.3.0/api/starknet_api_openrpc.json (supports array of transaction in fee estimation)

seems that version of starknet.js that you are using is v0.2.1 https://github.com/starkware-libs/starknet-specs/blob/v0.2.1/api/starknet_api_openrpc.json (supports only 1 single transaction object)

can you

**Comment by amanusk** [comment]
@mikiw for reference, I am using the latest version of starknet.js@next (5.11)
Would you know why there is no issue with Pathfinder using the same code?

(the repo I use to run these is here: https://github.com/amanusk/starknet-cli-wallet)

**Comment by mikiw** [comment]
As far as I know, Pathfinder supports v0.2.1 and partial support for v0.3.0 but sooner or later they will be supporting v0.3.0 fully.

Based on pathfinder releases notes https://github.com/eqlabs/pathfinder/releases.
