### ISSUE TITLE
ValueError when calling postman flush

### ISSUE THREAD

**Issue by mikiw** [0xSpaceShard/starknet-devnet#485]
**Describe the bug (observed vs expected behavior)**

when calling postman flush
```
curl -X POST http://localhost:5050/postman/flush -H 'Content-Type: application/json'
```

there is a `ValueError`
```
[2023-05-26 11:42:41 +0200] [1482] [ERROR] Exception on /postman/flush [POST]
Traceback (most recent call last):
  File "/home/mikiw/.cache/pypoetry/virtualenvs/starknet-devnet-Xwx3J2b3-py3.9/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mikiw/.cache/pypoetry/virtualenvs/starknet-devnet-Xwx3J2b3-py3.9/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mikiw/.cache/pypoetry/virtualenvs/starknet-devnet-Xwx3J2b3-py3.9/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/mikiw/.cache/pypoetry/virtualenvs/starknet-devnet-Xwx3J2b3-py3.9/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mikiw/.cache/pypoetry/virtualenvs/starknet-devnet-Xwx3J2b3-py3.9/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/mikiw/.cache/pypoetry/virtualenvs/starknet-devnet-Xwx3J2b3-py3.9/lib/python3.9/site-packages/asgiref/sync.py", line 240, in __call__
    return call_result.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/mikiw/.cache/pypoetry/virtualenvs/starknet-devnet-Xwx3J2b3-py3.9/lib/python3.9/site-packages/asgiref/sync.py", line 306, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/mnt/c/Workspace/ShardLabs/starknet-devnet/starknet_devnet/blueprints/postman.py", line 60, in flush
    result_dict = await state.starknet_wrapper.postman_flush()
  File "/mnt/c/Workspace/ShardLabs/starknet-devnet/starknet_devnet/starknet_wrapper.py", line 763, in postman_flush
    parsed_l1_l2_messages, transactions_to_execute = await self.l1l2.flush(state)
ValueError: not enough values to unpack (expected 2, got 0)
```

**Not reproducible on alpha-goerli**

- [ ] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**To Reproduce**

1. ...
2. ...
   ...

**Devnet version**

- I am using Devnet version:
- [ ] This happens with a dockerized Devnet (check the box if true).
- This does not appear on the following Devnet version:

**System specifications**

- OS:
- CPU:
- Memory:
- Python version:

**Comment by mikiw** [comment]
This issue is related to 'web3_contract_create_filter_fix' that was added in starkware code and our codebase recently on init of `__postman_wrapper`.

Later it was removed during 0.11.1 adaptations and it caused the flush function to fail.
